controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#register:
#  path: /register
#  controller: App\Controller\RegistrationController::register
#  methods: POST
  
api_login_check:
    path: /api/login